version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: '10'
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  e2e-executor: &e2e-executor
    requires:
      - build
    docker:
      - image: cypress/browsers:node10.16.0-chrome76

  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-deps-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-deps-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ./

jobs:
  lint:
    executor: node
    working_directory: ~/project

    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - persist_to_workspace:
          root: ./
          paths:
            - '*'
      # Build plugin
      - run: yarn build

  build:
    executor: node
    working_directory: ~/project

    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      # Build plugin
      - run: yarn build

  e2e_tests_asset_prefix:
    <<: *attach_workspace
    <<: *e2e-executor
    steps:
      - e2e-test:
          test_path: e2e-tests/asset-prefix
