version: 2.1

executors:
  node:
    parameters:
      image:
        type: string
        default: '10'
    docker:
      - image: circleci/node:<< parameters.image >>

aliases:
  e2e-executor: &e2e-executor
    docker:
      - image: cypress/browsers:node10.16.0-chrome76

  restore_cache: &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - yarn-deps-cache-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install node modules
      command: yarn --frozen-lockfile

  persist_cache: &persist_cache
    save_cache:
      name: Save node modules cache
      key: yarn-deps-cache-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache

  attach_workspace_project: &attach_workspace_project
    attach_workspace:
      at: ./

workflows:
  version: 2
  build-test:
    jobs:
      - bootstrap
      - lint:
          requires:
            - bootstrap
      - build:
          requires:
            - bootstrap
      - e2e_tests_asset_prefix:
          requires:
            - build
jobs:
  bootstrap:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *persist_cache
      - persist_to_workspace:
          root: ./
          paths:
            - '*'

  lint:
    executor: node
    working_directory: ~/project

    steps:
      - <<: *attach_workspace_project
      # Build plugin
      - run: yarn build

  build:
    executor: node
    working_directory: ~/project

    steps:
      - <<: *attach_workspace_project
      # Build plugin
      - run: yarn build

  e2e_tests_asset_prefix:
    <<: *e2e-executor
    working_directory: ~/project
    steps:
      - <<: *attach_workspace_project
      - run: cd e2e-tests/asset-prefix
      - run: yarn build
      - run: yarn test
